services:
  contacts-db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app

  api:
    image: oven/bun:1
    env_file:
      - .env
    # entrypoint: ["/bin/sh", "-c", "bun run dev"]
    command: /bin/sh -c "bun install && bun run dev"
    working_dir: /app
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    ports:
      - 3001:3001
    networks:
      - app
    depends_on:
      - contacts-db

  web:
    image: oven/bun:1
    # entrypoint: ["/bin/sh", "-c", "bun run dev"]
    command: /bin/sh -c "bun install && bun run dev"
    working_dir: /app
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - app
    depends_on:
      - api

networks:
  app:
    driver: bridge

volumes:
  postgres:
  api_node_modules:
  web_node_modules: