services:
  contacts-db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  api:
    build:
      context: ./api
    command: "bun start"
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
    networks:
      - app
    depends_on:
      - contacts-db

  web:
    build:
      context: ./web
    volumes:
      - ./src:/app/src
    ports:
      - 3000:80
    networks:
      - app

networks:
  app:

volumes:
  postgres:
