services:
  api:
    image: node:18-alpine
    container_name: api
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./api:/app
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - app


  # web:
  #   image: node:18-alpine
  #   container_name: web
  #   working_dir: /app
  #   command: sh -c "npm install && npm run start"
  #   volumes:
  #     - ./web:/app
  #   ports:
  #     - ${WEB_PORT}:${WEB_PORT}
  #   networks:
  #     - app
  #   depends_on:
  #     - api

networks:
  app:

volumes:
  postgres:
