# @host = http://localhost:3001
@host = https://contacts-jttveestu-gelutzs-projects.vercel.app
### Create categories
POST {{host}}/api/categories
Content-Type: application/json

{
  "name": "Family"
}

### Create contacts
POST {{host}}/contacts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phone": "123456789"
}

### Get all categories
GET {{host}}/categories

### Get all contacts
GET {{host}}/contacts
