services:
  contacts-db:
    image: postgres:15-alpine
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  # api:
  #   image: node:18-alpine
  #   container_name: api
  #   working_dir: /app
  #   command: sh -c "npm install && npm run dev"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   networks:
  #     - app
  #   depends_on:
  #     - contacts-db

  api:
    build:
      context: .
    command: "bun start"
    volumes:
      - ./src:/app/src
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - app
    depends_on:
      - contacts-db

networks:
  app:

volumes:
  postgres:
